name: CMake

on: [pull_request]


jobs:
  linux-check-all-libs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linalg_lib: [blis,openblas,netlib,intel-mkl]
        mpi_dist: [mpich]
        int_interface: [lp64,ilp64]
        thread: [sequential,openmp,pthreads]
        exclude:
          - linalg_lib: netlib
            int_interface: ilp64
          - linalg_lib: netlib
            thread: pthreads
          - linalg_lib: netlib
            thread: openmp
          - linalg_lib: intel-mkl
            thread: pthreads
    env:
      MKLROOT: /opt/intel/mkl
      CMAKE_PREFIX_PATH: '/home/software/install/${{matrix.linalg_lib}}-${{matrix.int_interface}}-${{matrix.thread}};/home/software/install/netlib-lp64-sequential'

    steps:
    - uses: actions/checkout@v2

    - name: Ubuntu Setup
      run: |
           apt list --installed | grep blas
           apt list --installed | grep lapack
           sudo apt-get -yq update && sudo apt-get install make wget curl libomp5
           sudo make -C .github/workflows/linalg install/main
           sudo make -C .github/workflows/linalg install/cmake
           sudo apt-get clean
           sudo make -C .github/workflows/linalg apt-add-repository/intel-mkl
           ls /usr/lib/x86_64-linux-gnu/ | grep blas

    - name: Setup MPI
      run: |
           ls /usr/lib/x86_64-linux-gnu/ | grep blas
           sudo make -C .github/workflows/linalg install/${{matrix.mpi_dist}}
           ls /usr/lib/x86_64-linux-gnu/ | grep blas


    - name: Build Linalg
      env:
        BUILD_TARGET: ${{matrix.linalg_lib}}/${{matrix.int_interface}}-${{matrix.thread}} 
      run: |
           ls /usr/lib/x86_64-linux-gnu/ | grep blas
           sudo make -C .github/workflows/linalg download/${{matrix.linalg_lib}} 
           sudo make -C .github/workflows/linalg install/${BUILD_TARGET}
           ls /usr/lib/x86_64-linux-gnu/ | grep blas

    - name: Add-On NETLIB
      if: ${{ matrix.linalg_lib != 'intel-mkl' && matrix.linalg_lib != 'netlib' && matrix.int_interface == 'lp64' }} 
      run: |
           ls /usr/lib/x86_64-linux-gnu/ | grep blas
           sudo make -C .github/workflows/linalg download/netlib
           sudo make -C .github/workflows/linalg install/netlib/lp64-sequential
           ls /usr/lib/x86_64-linux-gnu/ | grep blas









    - name: FindBLAS Default
      run: |
           ls /usr/lib/x86_64-linux-gnu/
           cmake -H${GITHUB_WORKSPACE}/examples/blas/default \
                 -B${{runner.workspace}}/build-findblas-default \
                 -DCMAKE_MODULE_PATH=${GITHUB_WORKSPACE} \
                 -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} \
                 -DIntelMKL_THREAD_LAYER=${{matrix.thread}}
           ls /usr/lib/x86_64-linux-gnu/

    - name: FindBLAS Integer Specific
      run: |
           ls /usr/lib/x86_64-linux-gnu/
           cmake -H${GITHUB_WORKSPACE}/examples/blas/${{matrix.int_interface}} \
                 -B${{runner.workspace}}/build-findblas-${{matrix.int_interface}} \
                 -DCMAKE_MODULE_PATH=${GITHUB_WORKSPACE} \
                 -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} \
                 -DIntelMKL_THREAD_LAYER=${{matrix.thread}}
           ls /usr/lib/x86_64-linux-gnu/



    - name: FindLAPACK Default
      if: ${{ matrix.linalg_lib != 'blis' || matrix.int_interface != 'ilp64' }}
      run: |
        cmake -H${GITHUB_WORKSPACE}/examples/lapack/default \
              -B${{runner.workspace}}/build-findlapack-default \
              -DCMAKE_MODULE_PATH=${GITHUB_WORKSPACE} \
              -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} \
              -DIntelMKL_THREAD_LAYER=${{matrix.thread}}

    - name: FindLAPACK Integer Specific
      if: ${{ matrix.linalg_lib != 'blis' || matrix.int_interface != 'ilp64' }}
      run: |
        cmake -H${GITHUB_WORKSPACE}/examples/lapack/${{matrix.int_interface}} \
              -B${{runner.workspace}}/build-findlapack-${{matrix.int_interface}} \
              -DCMAKE_MODULE_PATH=${GITHUB_WORKSPACE} \
              -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} \
              -DIntelMKL_THREAD_LAYER=${{matrix.thread}}

