name: CMake

on: [pull_request]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        thread: [serial,openmp,pthreads]
        linalg_lib: [blis,openblas,netlib]
        int_interface: [lp64,ilp64]
        exclude:
          - linalg_lib: netlib
            int_interface: ilp64
          - linalg_lib: netlib
            thread: [openmp,pthreads]

    steps:
    - uses: actions/checkout@v2

    - name: Ubuntu Setup
      run: |
           sudo apt-get -yq update && sudo apt-get install make wget curl libomp5
           sudo make -C .github/workflows/linalg install/main
           sudo make -C .github/workflows/linalg install/cmake

    - name: Build Linalg
      env:
        BUILD_TARGET: ${{matrix.linalg_lib}}/${{matrix.int_interface}}-${{matrix.thread}} 
      run: |
           sudo make -C .github/workflows/linalg download/${{matrix.linalg_lib}} 
           sudo make -C .github/workflows/linalg install/${BUILD_TARGET}
