name: CMake

on: [pull_request]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        thread: [serial,openmp,pthreads]
        linalg_lib: [blis,openblas,netlib]
        int_interface: [lp64,ilp64]
        exclude:
          - linalg_lib: netlib
          - int_interface: ilp64
        exclude:
          - linalg_lib: netlib
          - thread: [openmp,pthreads]

    steps:
    - uses: actions/checkout@v2

    - name: Ubuntu Setup
      run: |
           apt-get -yq update && apt-get install make wget curl
           make -C .github/workflows/linalg install/main
           make -C .github/workflows/linalg install/cmake

    - name: Build Linalg
      env:
        BUILD_TARGET: ${{matrix.linalg_lib}}/${{matrix.int_interface}}-${{matrix.thread}} 
      run: |
           make -C .github/workflows/linalg download/${{matrix.linalg_lib}} 
           make -C .github/workflows/linalg install/${BUILD_TARGET}
